version: '3.8'

services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: ${N8N_URL}/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      WEBHOOK_URL: ${N8N_URL}
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_HOST: 0.0.0.0
      VIRTUAL_HOST: n8n.onimock.ddnsfree.com
      LETSENCRYPT_HOST: n8n.onimock.ddnsfree.com
      LETSENCRYPT_EMAIL: seu@email.com
    volumes:
      - n8n_data:/home/node/.n8n
    expose:
      - '5678'
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    platform: linux/amd64
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    labels:
      - com.github.nginx-proxy.nginx
    networks:
      - proxy-tier

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: seu@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - acme_data:/etc/acme.sh
    networks:
      - proxy-tier

volumes:
  pgdata:
  redis_data:
  waha_sessions:
  waha_media:
  n8n_data:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  acme_data:

networks:
  proxy-tier:
    driver: bridge
